/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.company.search;

import com.company.common.Auth;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello Search");
        Auth auth = new Auth();
        System.out.println(auth.toString());
    }
}
