/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.company.refund;

import com.company.chatbot.User;
import com.company.common.Auth;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello Refund");
        Auth auth = new Auth();
        System.out.println(auth.toString());
        User user = new User();
        System.out.println(user.toString());
    }
}
